### ISSUE TITLE
I meet some problems when i run it on win10

### ISSUE THREAD

**Issue by lwhkop** [lzhbrian/deepfashion2-kps-agg-finetune#1]
Traceback (most recent call last):
  File "tools/train.py", line 248, in <module>
    main()
  File "tools/train.py", line 137, in main
    normalize,
  File "E:\DeepFashion2_Dataset\HRNet-Human-Pose-Estimation\tools\..\lib\dataset\deepfashion2.py", line 172, in __init__
    self.db = self._get_db()
  File "E:\DeepFashion2_Dataset\HRNet-Human-Pose-Estimation\tools\..\lib\dataset\deepfashion2.py", line 197, in _get_db
    gt_db = self._load_coco_person_detection_results()
  File "E:\DeepFashion2_Dataset\HRNet-Human-Pose-Estimation\tools\..\lib\dataset\deepfashion2.py", line 319, in _load_coco_person_detection_results
    det_res = all_boxes[n_img]
KeyError: 0

how to solve it?

**Comment by lzhbrian** [comment]
Hi, the code for dataset preparation has not released yet.
Seems like your code is having some problem with the dataset. If you can't wait, you can prepare the dataset as mentioned in the paper or readme.

**Comment by lwhkop** [comment]
> Hi, the code for dataset preparation has not released yet.
> Seems like your code is having some problem with the dataset. If you can't wait, you can prepare the dataset as mentioned in the paper or readme.

I prepared my dataset as mentioned in https://github.com/switchablenorms/DeepFashion2/issues/13. But I found some differents with your validation_coco.json. Seems you just use validation['annotations'] as your validation_coco.json? And I couldn't find where the key 'score' exist. Would you mind telling me the format of your validation_coco.json?
